# Read the Docs configuration file for MkDocs projects
# See https://docs.readthedocs.io/en/stable/config-file/v2.html for details

# Required
version: 2

# Set the version of Python and other tools you might need
build:
  os: ubuntu-22.04
  tools:
    python: "3.13"

# Install mkdocs macros and other plugins
# Per readthedocs: paths are relative to the root of the project.
python:
  install:
    - requirements: docs/requirements.txt

mkdocs:
  configuration: configurations/mtc-docs/mkdocs-mtc.yml
